### ISSUE TITLE
Question: Error with host volume on Mac OSX

### ISSUE THREAD

**Issue by ndtreviv** [pires/docker-elasticsearch#15]
Hi. I'm using your image, but am having trouble mounting the /data volume against a folder on my local machine.

The is the volume parameter I'm adding when I run docker run:
`-v /Users/myuser/data:/data`

This is the error I get when elasticsearch is started using your run.sh:
`Exception in thread "main" java.lang.IllegalStateException: Failed to created node environment
Likely root cause: java.nio.file.AccessDeniedException: /data/data
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
	at java.nio.file.Files.createDirectory(Files.java:674)
	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
	at java.nio.file.Files.createDirectories(Files.java:767)
	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:168)
	at org.elasticsearch.node.Node.<init>(Node.java:153)
	at org.elasticsearch.node.Node.<init>(Node.java:128)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:145)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:285)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
`

It looks like the elasticsearch user doesn't have permission to do anything in those directories, even though they've been chown-d to it in the run.sh.

What am I doing wrong here? Thanks for your help!

**Comment by ndtreviv** [comment]
Resolved: I overrode the image and changed the adduser/addgroup commands from:

`addgroup sudo 
adduser -D -g '' elasticsearch
addgroup elasticsearch sudo
`
to:

`adduser -D -g '' -u 1000 elasticsearch
addgroup -g 1000 elasticsearch sudo
`

As it turns out, when using Docker on a Mac, because the host directories are linked through the Docker VM, the user in the container image must have the same user ID or be in the same group as the docker user on the Docker VM. 

On my Docker VM, it's docker:1000 and staff:20

**Comment by devth** [comment]
@pires apparently the instructions in the README don't work on macOS due to the above issue. Trying to figure out how to resolve without overriding the image.

**Comment by ndtreviv** [comment]
My message above is quite old now, and since then native Docker for Mac has been released. Can you confirm that it's still a problem? Or are you still using the Linux VirtualBox VM?
