### ISSUE TITLE
Issues with kubernetes plugin and secrets

### ISSUE THREAD

**Issue by dermidgen** [pires/docker-elasticsearch#6]
@pires Thanks for your work on this.  I've been working on bringing this into https://github.com/pires/docker-elasticsearch-kubernetes and I'm having some troubles. It looks like the security context changes introduced in ES 2 prevent the kubernetes plugin from being able to read `/var/run/secrets/kubernetes.io/serviceauth/ca.crt`.

After employing some workarounds to get the cert into the kubernetes plugin, it was hitting further permissions errors:

```
io.fabric8.kubernetes.client.KubernetesClientException: Error executing: GET at: https://kubernetes.default.svc/api/v1/namespaces/default/endpoints/elasticsearch. Cause: access denied ("java.net.NetPermission" "getProxySelector")
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestException(OperationSupport.java:245)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:182)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleGet(OperationSupport.java:173)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleGet(BaseOperation.java:472)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.get(BaseOperation.java:105)
	at io.fabric8.elasticsearch.cloud.kubernetes.KubernetesAPIServiceImpl.endpoints(KubernetesAPIServiceImpl.java:27)
	at io.fabric8.elasticsearch.discovery.kubernetes.KubernetesUnicastHostsProvider.buildDynamicNodes(KubernetesUnicastHostsProvider.java:81)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.sendPings(UnicastZenPing.java:316)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing$2$1.doRun(UnicastZenPing.java:234)
	at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.security.AccessControlException: access denied ("java.net.NetPermission" "getProxySelector")
	at java.security.AccessControlContext.checkPermission(AccessControlContext.java:472)
	at java.security.AccessController.checkPermission(AccessController.java:884)
	at java.lang.SecurityManager.checkPermission(SecurityManager.java:549)
	at java.net.ProxySelector.getDefault(ProxySelector.java:94)
	at com.squareup.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java:614)
	at com.squareup.okhttp.Call.<init>(Call.java:48)
	at com.squareup.okhttp.OkHttpClient.newCall(OkHttpClient.java:595)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:180)
```

I've got an issue open https://github.com/fabric8io/elasticsearch-cloud-kubernetes/issues/18 to see if they can lend a hand here.

@pires any thoughts?

**Comment by pires** [comment]
Yeah, I faced this as well and that's why I haven't upgraded to 2.0.0 on Kubernetes. Let's keep this discussion on the issue you created upstream.
